### ISSUE TITLE
How do I get from a grapheme defined in transcriptiondata to the sound?

### ISSUE THREAD

**Issue by xrotwang** [cldf-clts/pyclts#11]
We do have a lookup `resolve_sound` to go from a CLTS `Sound` or from a BIPA grapheme to the corresponding grapheme(s) in a given `Transcriptiondata` class. But how do I get the reverse lookup?
In the case at hand, I tried to get CLTS `Sound`s for the APiCS segments. Somewhat naively, I tried
```python
>>> from pyclts import CLTS
>>> apics = CLTS('clts').transcriptiondata('apics')
>>> apics['a']
```
And this works for most of the APiCS graphemes - but only because these graphemes are also defined in BIPA. Luckily, there are some APiCS graphemes for which this fails (lucky, because it showed that I was doing it wrong), e.g. `<sup>m</sup>b`.

But how then am I supposed to retrieve the BIPA equivalent for `<sup>m</sup>b`? `TranscriptionData` seems to be missing a `resolve_grapheme` method - or am *I* missing something?

**Comment by LinguList** [comment]
I think, this is true, let me have a look...

**Comment by LinguList** [comment]
```python
In [31]: to_bipa = {}                                                           

In [32]: for row in apics.data.values(): 
    ...:     for row2 in row: 
    ...:         to_bipa[row2['grapheme']] = row2['bipa_grapheme'] 
    ...:                                                                        

In [33]: to_bipa['<sup>m</sup>p']                                               
Out[33]: 'ⁿp'
```

**Comment by LinguList** [comment]
We miss a lookup from grapheme to bipa. We could add it as a property. The problem is that bipa can merge two sounds (as we did with k<sup>wh</sup> vs. k<sup>hw</sup> in phoible version 1), which is why the dictionary maps one bipa to a list (as shown in my quick code for row2).

**Comment by LinguList** [comment]
For the question of how to make an approximate mapping, I would say that we cannot do this: we do it in the initial code where we link the data up. So if apics has a new sound, that we don't have in bipa, we need to manually add it. But I think you were rather asking for the reverse lookup, right? In that case, I'd say, it should be added to pyclts, as it is useful, also, e.g., for phoible, etc.

**Comment by xrotwang** [comment]
Yes, I'm also leaning towards adding a `resolve_grapheme` method (if only to make it clear that `resolve_sound` is **not** supposed to do this). I'd probably even implement this via a `dict` `grapheme_lookup` which is computed in `__init__`. Will send PR soon.

**Comment by LinguList** [comment]
Nice. It reflects that we were not really using clts much apart from for
our own data, but if we start back-integrating clts into the other
datasets, this will hopefully also increase awareness and also help us
to keep maintaining clts and improving it (in terms of mapping to datasets).

**Comment by xrotwang** [comment]
Yes, use cases like a "unified way to compute IPA charts" do help.
