### ISSUE TITLE
Started support for IPA charts for BIPA inventories

### ISSUE THREAD

**Issue by xrotwang** [cldf-clts/pyclts#14]
I failed to turn this into a PR, so here's an issue for code review.

So here's initial support for displaying IPA charts for sets of BIPA sounds. The code is in [ipachart.py](https://github.com/cldf-clts/pyclts/blob/master/src/pyclts/ipachart.py) and the idea is as follows:

1. The various parts of the IPA charts are designed as [`Diagram`](https://github.com/cldf-clts/pyclts/blob/6943229a9d92bd7b0b6a5239d5cde967c6447ae3/src/pyclts/ipachart.py#L93) subclasses.
2. These have an associated HTML template (SVG in the case of the vowel trapezoid), which specifies "slots" via lists of CLTS features in attributes of container elements.
3. The `Diagram` class knows how to match segments from an inventory to slots in the template, and thus can `render` the template.

Since slots are defined in terms of CLTS features and **not** as white-list of individual BIPA graphemes, a lot more segments match each slot. But as far as I understand, that is what we want, right? E.g. there is not really a need for multiple vowel diagrams, when most vowels in an inventory fit into one?

I'll attach a couple of examples of APiCS inventories (as HTML pages) below:

- https://apics-online.info/contributions/3#tipa

[apics3.txt](https://github.com/cldf-clts/pyclts/files/4669025/apics3.txt)

- https://apics-online.info/contributions/10#tipa

[apics10.txt](https://github.com/cldf-clts/pyclts/files/4669026/apics10.txt)

Regarding the other standard IPA tables, I'm not sure. They seem to just list stuff in a way that doesn't seem to convey any semantics - so I'd be tempted to replace them with tables for CLTS `Sound` subclasses, à la
- "Other consonants"
- "Clicks"
- "Clusters"
- "Diphtongs"

(I don't know, why Implosives are not included in the table of pulmonic consonants, though. They seem to fit as additional "manner".)

**Comment by xrotwang** [comment]
@LinguList I could try to use this machinery to include IPA charts in lsi. This could be done at db import time, using sets of segments per language as inventory.

**Comment by LinguList** [comment]
Sounds good. Let me know if help is needed!

**Comment by xrotwang** [comment]
@LinguList I'd need input regarding 
- why implosives cannot simply be incorporated into the place/manner table of consonants
- if displaying clusters, clicks and diphtongs simply as lists per each would be sufficient.

**Comment by LinguList** [comment]
Okay, implosives as manner is good. And yes, the others as list is also sufficient!

**Comment by xrotwang** [comment]
first implementation done and released in v2.1
