### ISSUE TITLE
Translation from BIPA to ASJP does not always work as expected

### ISSUE THREAD

**Issue by XachaB** [cldf-clts/pyclts#23]
The documentation shows this example:

~~~
>>> asjp = clts.transcriptionsystem('asjpcode')
>>> clts.bipa.translate('ts a ŋ ə', asjp)
'c E N 3'
~~~

It so happens that this seems to fail for the phoneme "ð":

~~~
>>> clts.bipa.translate("ð", asjp) 
'<?><!>'
~~~

I can get the value I want by using directly the dictionnary:

~~~
>>> clts.soundclasses_dict["asjp"]["ð"]
'8'
~~~

I did not check if other phonemes were affected. Is this a bug ?

**Comment by LinguList** [comment]
asjp does not have the voiced dental fricative, so we cannot translate to it! 8 is the voiceless one!

**Comment by XachaB** [comment]
Brown et al 2013 give "8" for both:
![image](https://user-images.githubusercontent.com/5927813/99555980-3afcb900-29c1-11eb-94e4-9ca2a43ea674.png)

[Wikipedia gives the same thing](https://en.wikipedia.org/wiki/Automated_Similarity_Judgment_Program#ASJPcode):


ASJPcode | Description | IPA
-- | -- | --
i | high front vowel, rounded and unrounded | i, ɪ, y, ʏ
e | mid front vowel, rounded and unrounded | e, ø
E | low front vowel, rounded and unrounded | a, æ, ɛ, ɶ, œ
3 | high and mid central vowel, rounded and unrounded | ɨ, ɘ, ə, ɜ, ʉ, ɵ, ɞ
a | low central vowel, unrounded | ɐ
u | high back vowel, rounded and unrounded | ɯ, u
o | mid and low back vowel, rounded and unrounded | ɤ, ʌ, ɑ, o, ɔ, ɒ
p | voiceless bilabial stop and fricative | p, ɸ
b | voiced bilabial stop and fricative | b, β
m | bilabial nasal | m
f | voiceless labiodental fricative | f
v | voiced labiodental fricative | v
8 | voiceless and voiced dental fricative | θ, ð

etc.

**Comment by LinguList** [comment]
Yes, but our feature system does not accept "both".

**Comment by LinguList** [comment]
We had a discussion on transcription systems very early, and decided to
accept this very kind of failure, since it would disrupt our system, if
we start by saying: this sound is voiced AND voiceless. Adjusting the
translation function would disrupt our rather rigorous testing. So we
offer sound classes as an alternative ;)

**Comment by XachaB** [comment]
The implementation choice of avoiding underspecified sounds makes sense. I think some issues remain for users:

- For users this makes `clts.bipa.translate('ts a ŋ ə', asjp)` very misleading: what is the use case here ? A user who would want to translate words which use only a narrow subset of ASJPcode ? There is no warning about this in the documentation, and users would probably assume, as I did, that this is the way to translate from bipa to asjpcode.

- The alternative `clts.soundclasses_dict["asjp"]["ð"]` works. However, it does not translate to ASJPcode (as defined by Brown et al 2008, 2013, etc), but to a clts/lingpy specific version, which we could call ASJPclts, where integers below 6 are re-mapped to tones, and alternative letters are used for these. I understand why this was done, to avoid confusions with tones, but it is confusing for users.

~~~
>>> clts = CLTS("/home/sacha/.config/cldf/clts")
>>> asjp = clts.transcriptionsystem('asjpcode')
>>> clts.bipa.translate('ə', asjp) # this gives ASJPcode, but only for a subset of characters
'3'
>>> clts.soundclasses_dict["asjp"]['ə']  # this gives ASJPclts
'I'
~~~

For end-users, this means that clts does not provide any way to translate from BIPA to ASJPcode for all valid ASJPcode characters. Moreover, the fact that both  `clts.bipa.translate` and `clts.soundclasses_dict["asjp"]` look like they are made to do that is very misleading and can lead to bugs.

In the end the solution for me was to write my own mapping. I think clts should either provide the functionnality, or make sure it is clear it does not.

**Comment by LinguList** [comment]
So far, nobody has complained about this. Why so? Because not many
people really want to translate TO asjp. Since ASJP code is largely
underspecified, and there's no mapping, the translation does not work.
If you look at the Python standard library, you will also see that
"translate" is a string-function that takes a mapping by characters. You
should think of the translate function here in the same way. As to your
mapping from bipa to asjp (I assume it does not work to UPA, APA, etc.
?), you are cordially invited to submit it to our library (ideally
providing some tests as well). It would be a shame if that work is not
shared.

**Comment by XachaB** [comment]
Ok, no problem, this just means that my need happens to fall out of the expected use cases for clts. 

Regarding what I have: it is simply a mapping based on the profile in the lexibank/asjp repository (with a few things added). 
It would take me much more time than I currently have available to integrate it to CLTS (of which I don't yet know all the intricacies) or write tests, but here is the list of pairs, in case anyone has the skills and time to integrate it:

~~~
[('ttS~"', 'tʃ’ː'), ('y*', 'j̃'), ('tw~"', 't’ʷ'), ('kw~"', 'k’ʷ'),
 ('Sw~"', 'ʃ’ʷ'), ('w*', 'w̃'), ('^w~', 'w'), ('l*', 'l̃'), ('r*', 'r̃'),
 ('TS~', 'cʃ'), ('^h~', 'h'), ('wp~', 'ʷp'), ('wb~', 'ʷb'), ('wN~', 'ʷŋ'),
 ('wq~', 'ʷq'), ('s"y~', 's’ʲ'), ('vy~"', 'v’ʲ'), ('y~', 'j'), ('tS~h~', 'tʃʰ'),
 ('q""', 'qʼ'), ('g"w~', 'g’ʷ'), ('d"w~', 'd’ʷ'), ('!', 'ǃ'), ('!"', 'ǃ’'),
 ('!"~', 'ǃ’'), ('!7~', 'ǃˀ'), ('!N~', 'ǃⁿ'), ('!S~', 'ǂ'), ('!g~', 'ǂ'),
 ('!h~', 'ǃʰ'), ('!k~', 'ǂ'), ('!n~', 'ǃⁿ'), ('!t~', 'ǀ'), ('!w~', 'ǃʷ'),
 ('!x~', 'ǂ'), ('N!~', 'ⁿǂ'), ('g!~', 'ǂ'), ('m!~', 'ⁿǂ'), ('n!~', 'ⁿǃ'),
 ('q!~', 'ǂ'), ('!"w~', 'ǃ’ʷ'), ('E', 'a'), ('E*', 'ã'), ('f', 'f'),
 ('v', 'v'), ('f"', 'fʼ'), ('5v~', 'ⁿv'), ('fh~', 'fʰ'), ('fw~', 'fʷ'),
 ('fy~', 'fʲ'), ('hv~', 'ʰv'), ('nv~', 'ⁿv'), ('pf~', 'pf'), ('v7~', 'vˀ'),
 ('vh~', 'vʰ'), ('vx~', 'vˠ'), ('vy~', 'vʲ'), ('T', 'c'), ('c', 'ts'),
 ('T"', 'cʼ'), ('5T~', 'ⁿc'), ('NT~', 'ⁿc'), ('Th~', 'cʰ'), ('Tj~', 'cʲ'),
 ('Tw~', 'cʷ'), ('Ty~', 'cʲ'), ('c7~', 'tsˀ'), ('ch~', 'tsʰ'), ('cw~', 'tsʷ'),
 ('cx~', 'tsˠ'), ('dz~', 'dz'), ('nT~', 'ⁿc'), ('tc~', 'ts'), ('tn~', 'tⁿ'),
 ('ts~', 'ts'), ('T"y~', 'c’ʲ'), ('c"w~', 'ts’ʷ'), ('cyw~', 'tsʲʷ'), ('8', 'θ'),
 ('8"', 'θ’'), ('87~', 'θˀ'), ('8X~', 'θˠ'), ('8h~', 'θʰ'), ('8y~', 'θʲ'),
 ('n8~', 'ⁿθ'), ('3', 'ə'), ('a', 'ɐ'), ('e', 'e'), ('3*', 'ə̃'), ('a*', 'ɐ̃'),
 ('e*', 'ẽ'), ('a*7~', 'ɐ̃ˀ'), ('X', 'χ'), ('x', 'x'), ('X"', 'χʼ'),
 ('x"', 'xʼ'), ('5X~', 'ⁿχ'), ('7x~', 'ˀx'), ('XX~', 'χː'), ('Xw~', 'χʷ'),
 ('Xy~', 'χʲ'), ('hX~', 'ʰχ'), ('hx~', 'ʰx'), ('x7~', 'xˀ'), ('xh~', 'xʰ'),
 ('xw~', 'xʷ'), ('xy~', 'xʲ'), ('X"w~', 'χ’ʷ'), ('x"w~', 'x’ʷ'),
 ('xw"~', 'x’ʷ'), ('7', 'ʔ'), ('h', 'h'), ('7"', 'ʔ’'), ('h"', 'h’'),
 ('7h~', 'ʔʰ'), ('7w~', 'ʔʷ'), ('7y~', 'ʔʲ'), ('N7~', 'ⁿʔ'), ('hw~', 'hʷ'),
 ('hy~', 'hʲ'), ('7"w~', 'ʔ’ʷ'), ('h"w~', 'h’ʷ'), ('i', 'i'), ('i*', 'ĩ'),
 ('y', 'j'), ('y"', 'j’'), ('y7~', 'jˀ'), ('G', 'ɢ'), ('g', 'g'), ('k', 'k'),
 ('q', 'q'), ('g"', 'g’'), ('k"', 'kʼ'), ('q"', 'qʼ'), ('7g~', 'ˀg'),
 ('Gw~', 'ɢʷ'), ('NG~', 'ⁿɢ'), ('Ng~', 'ⁿg'), ('Ngw~', 'ⁿgʷ'), ('Nk~', 'ⁿk'),
 ('Nq~', 'ⁿq'), ('g7~', 'gˀ'), ('gh~', 'gʰ'), ('gw~', 'gʷ'), ('gx~', 'gɣ'),
 ('gy~', 'gʲ'), ('hk~', 'ʰk'), ('hq~', 'ʰq'), ('k7~', 'kˀ'), ('kN~', 'kˠ'),
 ('kX~', 'kˠ'), ('kh~', 'kʰ'), ('kj~', 'kʲ'), ('kp~', 'kp'), ('kpw~', 'kpʷ'),
 ('kw~', 'kʷ'), ('kx~', 'kˠ'), ('ky~', 'kʲ'), ('ng~', 'ⁿg'), ('nk~', 'ⁿk'),
 ('q7~', 'qˀ'), ('qX~', 'qχ'), ('qh~', 'qʰ'), ('qw~', 'qʷ'), ('qy~', 'qʲ'),
 ('Nk"~', 'ⁿk’'), ('k"w~', 'kʼʷ'), ('k"y~', 'k’ʲ'), ('kwh~', 'kʷʰ'),
 ('kx"~', 'k’ˠ'), ('ky"~', 'k’ʲ'), ('nk"~', 'ⁿk’'), ('q"X~', 'q’ˠ'),
 ('q"w~', 'qʼʷ'), ('qw"~', 'qʼʷ'), ('L', 'ʎ'), ('l', 'l'), ('L"', 'ʎ’'),
 ('l"', 'l’'), ('L7~', 'ʎˀ'), ('LX~', 'ʎˠ'), ('Lh~', 'ʎʰ'), ('Lw~', 'ʎʷ'),
 ('Ly~', 'ʎʲ'), ('hl~', 'ʰl'), ('l7~', 'lˀ'), ('lX~', 'lˠ'), ('lZ~', 'ɮ'),
 ('lh~', 'lʰ'), ('lw"', 'l’ʷ'), ('lw~', 'lʷ'), ('lx~', 'lˠ'), ('ly~', 'lʲ'),
 ('nlh~', 'ⁿlʰ'), ('m', 'm'), ('m"', 'm’'), ('hm~', 'ʰm'), ('m7~', 'mˀ'),
 ('mX~', 'mˠ'), ('mh~', 'mʰ'), ('mm~', 'mː'), ('mp~', 'mp'), ('mw~', 'mʷ'),
 ('mx~', 'mˠ'), ('my~', 'mʲ'), ('%', 'ɲ'), ('4', 'n̪'), ('5', 'ɲ'), ('N', 'ŋ'),
 ('n', 'n'), ('5"', 'ɲ’'), ('N"', 'ŋ’'), ('n"', 'n’'), ('4h~', 'n̪ʰ'),
 ('5h~', 'ɲʰ'), ('5w~', 'ɲʷ'), ('5y~', 'ɲʲ'), ('7n~', 'ˀn'), ('Nh~', 'ŋʰ'),
 ('Nn~', 'ŋ'), ('Nw~', 'ŋʷ'), ('Nx~', 'ŋˠ'), ('Ny~', 'ŋʲ'), ('h5~', 'ʰɲ'),
 ('hN~', 'ʰŋ'), ('hn~', 'ʰn'), ('n7~', 'nˀ'), ('nh~', 'nʰ'), ('nw~', 'nʷ'),
 ('nx~', 'nˠ'), ('ny~', 'nʲ'), ('yn~', 'ɲ'), ('hNq~', 'ʰŋˠ'), ('n5w~', 'ɲʷ'),
 ('b', 'b'), ('p', 'p'), ('b"', 'b’'), ('p"', 'pʼ'), ('7b~', 'ˀb'),
 ('Nb~', 'ⁿb'), ('Np~', 'ⁿp'), ('b7~', 'bˀ'), ('bX~', 'bˠ'), ('bg~', 'bˠ'),
 ('bh~', 'bʰ'), ('bw~', 'bʷ'), ('bx~', 'bˠ'), ('by~', 'bʲ'), ('hp~', 'ʰp'),
 ('mb~', 'ⁿb'), ('mbw~', 'ⁿbʷ'), ('np~', 'ⁿp'), ('p7~', 'pˀ'), ('pS~', 'pʃ'),
 ('pX~', 'pˠ'), ('ph~', 'pʰ'), ('pw~', 'pʷ'), ('px~', 'pˠ'), ('py~', 'pʲ'),
 ('b"w~', 'b’ʷ'), ('b"y~', 'b’ʲ'), ('p"X~', 'pχʼ'), ('p"y~', 'p’ʲ'),
 ('pf"~', 'pfʼ'), ('r', 'r'), ('r"', 'r’'), ('Nr~', 'ⁿr'), ('hr~', 'ʰr'),
 ('r7~', 'rˀ'), ('rX~', 'rˠ'), ('rh~', 'rʰ'), ('rj~', 'rʲ'), ('rr~', 'rː'),
 ('rw~', 'rʷ'), ('rx~', 'rˠ'), ('ry~', 'rʲ'), ('S', 'ʃ'), ('Z', 'ʒ'),
 ('s', 's'), ('z', 'z'), ('S"', 'ʃʼ'), ('Z"', 'ʒ’'), ('s"', 'sʼ'), ('z"', 'z’'),
 ('5Z~', 'ⁿʒ'), ('7S~', 'ˀʃ'), ('7s~', 'ˀs'), ('Ns~', 'ⁿs'), ('S7~', 'ʃˀ'),
 ('SX~', 'ʃˠ'), ('Sh~', 'ʃʰ'), ('Sw~', 'ʃʷ'), ('Sx~', 'ʃˠ'), ('Sy~', 'ʃʲ'),
 ('Z7~', 'ʒˀ'), ('ZX~', 'ʒˠ'), ('ZZ~', 'ʒː'), ('Zh~', 'ʒʰ'), ('Zj~', 'ʒʲ'),
 ('Zw~', 'ʒʷ'), ('Zy~', 'ʒʲ'), ('hS~', 'ʰʃ'), ('hs~', 'ʰs'), ('nS~', 'ⁿʃ'),
 ('nZ~', 'ⁿʒ'), ('ns~', 'ⁿs'), ('nz~', 'ⁿz'), ('s7~', 'sˀ'), ('sX~', 'sˠ'),
 ('sh~', 'sʰ'), ('ss~', 'sː'), ('sw~', 'sʷ'), ('sx~', 'sˠ'), ('sy~', 'sʲ'),
 ('zX~', 'zˠ'), ('zh~', 'zʰ'), ('zw~', 'zʷ'), ('zy~', 'zʲ'), ('zz~', 'zː'),
 ('S"h~', 'ʃ’ʰ'), ('S"w~', 'ʃ’ʷ'), ('C', 'tʃ'), ('d', 'd'), ('j', 'dʒ'),
 ('t', 't'), ('C"', 'tʃʼ'), ('c"', 'tsʼ'), ('d"', 'd’'), ('j"', 'dʒ’'),
 ('t"', 'tʼ'), ('5C~', 'ⁿtʃ'), ('5d~', 'ⁿd'), ('7C~', 'ˀtʃ'), ('7d~', 'ˀd'),
 ('7j~', 'ˀdʒ'), ('C7~', 'tʃˀ'), ('CS~', 'tʃ'), ('CX~', 'tʃˠ'), ('Ch~', 'tʃʰ'),
 ('Cw~', 'tʃʷ'), ('Cx~', 'tʃˠ'), ('Cy~', 'tʃʲ'), ('NC~', 'ⁿtʃ'), ('Nd~', 'ⁿd'),
 ('Nt~', 'ⁿt'), ('cy~', 'tsʲ'), ('d7~', 'dˀ'), ('dX~', 'dˠ'), ('dZ~', 'dʒ'),
 ('dh~', 'dʰ'), ('dj~', 'dʒ'), ('dn~', 'dⁿ'), ('dw~', 'dʷ'), ('dx~', 'dˠ'),
 ('dy~', 'dʲ'), ('hC~', 'ʰtʃ'), ('hc~', 'ʰts'), ('ht~', 'ʰt'), ('j7~', 'dʒˀ'),
 ('jX~', 'dʒˠ'), ('jZ~', 'dʒ'), ('jh~', 'dʒʰ'), ('jw~', 'dʒʷ'), ('jy~', 'dʒʲ'),
 ('md~', 'ⁿd'), ('nC~', 'ⁿtʃ'), ('nc~', 'ⁿts'), ('nd~', 'ⁿd'), ('nj~', 'ⁿdʒ'),
 ('nt~', 'ⁿt'), ('t7~', 'tˀ'), ('tS~', 'tʃ'), ('th~', 'tʰ'), ('tj~', 'tʲ'),
 ('tt~', 'tː'), ('tw~', 'tʷ'), ('tx~', 'tˠ'), ('ty~', 'tʲ'), ('C"w~', 'tʃ’ʷ'),
 ('C"y~', 'tʃ’ʲ'), ('c"X~', 'tʃ’ˠ'), ('c"y~', 'ts’ʲ'), ('nc"~', 'ⁿtsʼ'),
 ('nt"~', 'ⁿt’'), ('t"8~', 'tθ’'), ('t"X~', 't’ˠ'), ('t"h~', 't’ʰ'),
 ('t"w~', 't’ʷ'), ('t"y~', 't’ʲ'), ('thw~', 'tʷʰ'), ('o', 'o'), ('o*', 'õ'),
 ('w', 'w'), ('w"', 'w’'), ('w7~', 'wˀ'), ('u', 'u'), ('u*', 'ũ'),
 ('u7~', 'uˀ') ("*", "*"), ]
~~~

This is missing a few clusters which I had a hard time interpreting.

At first, I wanted to downscale BIPA to ASJPcode in order to reproduce results from Brown et al 2013 on lexibank datasets. In order to keep using CLTS in lexitools rather than a custom mapping, I settled for producing results in ASJP-clts. This meant that they were not comparable anymore to results from the original study, which uses ASJPcode. I then needed to map from ASJPcode values to ASJP-clts. I used BIPA as a pivot: from ASJPcode to BIPA by building a dict from the above pairs, then from BIPA to ASJP-clts by using the sound classes dict.

**Comment by LinguList** [comment]
Well, this is also an orthography profile, right? And this was checked
WITH CLTS! So why not just submit it as an orthography profile to
cldf/orthograpy?

**Comment by XachaB** [comment]
I'm not sure I understand what you mean, can you explain what cldf/orthography is, and how it interacts with this question ? 

In the end I capitulated and am simply skipping anything that can't be translated using `asjp.translate(<asjp string>, clts.bipa)`.

**Comment by XachaB** [comment]
I was referring from the profile from here: [lexibank/asjp/etc/orthography.tsv](https://github.com/lexibank/asjp/blob/master/etc/orthography.tsv), skipping anything that has spaces in the IPA. But really, in the end, this was not a good solution, because I still lost clusters when going from BIPA to ASJP-clts using the sound class dictionary.

**Comment by LinguList** [comment]
Never mind. I do not have time to follow up on this discussion now,
specifically also because I do not see any reason why I would translate
a dataset into ASJP code, given that this is by no means helpful anyway.
