### ISSUE TITLE
Improvements to `TranscriptioData`

### ISSUE THREAD

**Issue by tresoldi** [cldf-clts/pyclts#34]
The usage of `TranscriptionData` to map a grapheme in a dataset to a CLTS sound (i.e., `.resolve_grapheme()`) does not seem to be documented, and raises an exception (ValueError) if we pass a a grapheme not in the list.

As it is arguably one of the main intended usages of the class, I would suggest we:

  - add a `.__get__()` method that wraps `.resolve_grapheme()`, so we can do calls like `phoible["bɾ"]`
  - patch `.resolve_grapheme()` to return an `UnknownSound` instead of raising an exception (but note that this is not totally symmetric with `.resolve_sound()`.

I can prepare a PR for that, it accepted.

**Comment by tresoldi** [comment]
Pinging @LinguList and @xrotwang

**Comment by LinguList** [comment]
So to clarify, you have a sound in Phoible's original grapheme list, and want the corresponding BIPA sound, right?

**Comment by tresoldi** [comment]
Yes, it is for the inventory study. I can get the CLTS sound with `phoible.resolve_grapheme(grapheme)` (with `phoible` the `clts.transcriptiondata("phoible")`, but I did not find documentation for it.

Using `phoible[grapheme]` would make it more similar to transcription systems, and there is also the issue that it currently raises an exception if the grapheme is not listed (in this case, due to using the development version of Phoible, while the mapping in CLTS data follows the last released version).

**Comment by LinguList** [comment]
If you check [lexibank/allenbai](https://githib.com/lexibank/allenbai) as well as the code that I wrote for the inventory comparison in lexicore (will be moved to lexibanklater, now lexibank/pylexicore) you will see that we have another way to proceed here:

https://github.com/lexibank/allenbai/blob/c2f52114da97334dc63f8d2fafe5b308f2031924/lexibank_allenbai.py#L116-L118

Every `td` has its `grapheme_map` attribute that allows to access the BIPA sound for a corresponding original grapheme. 

The essential code is here:

https://github.com/cldf-clts/pyclts/blob/956b07297b1402c39403b7c40e8f32d4eb24bae9/src/pyclts/util.py#L72-L85

**Comment by tresoldi** [comment]
Ok, I will do it this way.
