### ISSUE TITLE
modify the Inventory class to be able to be integrated with lexibank / lexicore wordlists

### ISSUE THREAD

**Issue by LinguList** [cldf-clts/pyclts#36]
In my first proposal for a handling of inventory data, which is quite satisfying in terms of handling, also allowing us to operationalize several phonological features in wals, I used a somewhat modified version of the current Inventory class. I propose to bring the classes in sync, and to use then the pyclts-class for inventories as the standard class that is imported from pylexibank when adding wordlist code there.

**Comment by LinguList** [comment]
@tresoldi, do you actively use the inventory code now? 

I am asking, since my proposed changes would affect the code to some degree (not negatively, but you might have to adjust the handling).

**Comment by tresoldi** [comment]
Yes, I am using it: https://github.com/lexibank/lexitools/blob/1c7cbb16b5c068d217f1ec6f89313fd50e6a4447/src/lexitools/commands/inventorycompare.py#L213

But no problem, I can update it. It seems transparent, but if not I will ask you.
