### ISSUE TITLE
Should __call__ operate on lists?

### ISSUE THREAD

**Issue by tresoldi** [cldf-clts/pyclts#7]
Marginally related to https://github.com/cldf-clts/pyclts/issues/2 , at the moment `__call__` only accepts strings and not lists:

```python
>>> from pyclts import CLTS
>>> clts = CLTS("/home/tresoldi/.config/cldf/clts")
>>> sca = clts.soundclass("sca")
>>> sca("m a m a")
['M', 'A', 'M', 'A']
>>> sca(["m", "a", "m", "a"])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tresoldi/repos/clts-test/env/lib/python3.5/site-packages/pyclts/util.py", line 43, in __call__
    return [self.get(x, default=default) for x in sounds.split()]
AttributeError: 'list' object has no attribute 'split'
```

In some situations, particularly when translating to sound classes as above, it might make sense to accepts lists. The change to support this would be minor: at https://github.com/cldf-clts/pyclts/blob/4842f1fd9613de6ef20a917dbc3bd723e8d0ffbb/src/pyclts/util.py#L42 (as per the traceback above) we could check the type of `sounds` with `isinstance` and, in case of strings, split it. The list comprehension would become `return [self.get(x, default=default) for x in sounds]`.

**Comment by tresoldi** [comment]
Pinging @LinguList and @xrotwang

**Comment by xrotwang** [comment]
Seems reasonable. Can you put together a PR?

**Comment by LinguList** [comment]
Yep, agreed.
